<?php require('includes/header.php'); ?>


<!-- Page d'édition d'un article -->
<h2><i class="fa fa-pencil"></i> Editer un article</h2>

<!-- Formulaire de mise à jour d'un article -->

    <form class="generic-form" action="edit_post.php" method="post">
        <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i>Edition d'article</legend>

            <ul>

                <li>
                    <label for="title">Titre :</label>
                    <input type="text" id="title" name="title" value="<?=htmlspecialchars($art['title'])?>">
                </li>
                <li style="margin:0">
                    <label class="textarea" for="contents">Article :</label>
                    <textarea id="contents" name="contents" rows="15"><?=htmlspecialchars($art['content'])?></textarea>
                </li>
                <li>
                    <label for="author">Auteur :</label>

                    <select id="author" name="author">

                        <?php

                        foreach ($auts as $author) {

                            echo '<option selected value="'.htmlspecialchars($author['id_author']).'">' . htmlspecialchars($author['name_author']) . '</option>';

                        }

                        ?>

                    </select>
                </li>
                <li>
                    <label for="category">Catégorie :</label>

                    <select id="category" name="category">

                        <?php

                        foreach ($cats as $category){

                            echo '<option selected value="'.htmlspecialchars($category['id_cat']).'">' . htmlspecialchars($category['name_cat']) . '</option>';

                        }

                        ?>

                    </select>

                </li>
                <li>
                    <button class="button button-primary" type="submit">Enregistrer</button>
                    <a class="button button-cancel" href="index.php">Annuler</a>
                </li>

            </ul>
        </fieldset>
        <input type="hidden" name="id_art" value="<?= htmlspecialchars($_GET['id_art']) ?? 'devrait avoir id article' ?>">
    </form>


<?php require('includes/footer.php'); ?>
